### ISSUE TITLE
Handle glob imports

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [SectorLabs/babel-plugin-transform-named-imports#1]
First, great idea! I was excited to see this 😄 

One issue came up when I tried to run it over our codebase: the plugin doesn't know to opt-out of trying to trace namespace / "glob" imports like:

```js
import * as something from './somewhere';
```

**Comment by Photonios** [comment]
Fixed and released in 1.0.2-beta:

https://github.com/SectorLabs/babel-plugin-transform-named-imports/releases/tag/v1.0.2-beta
