### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [SectorLabs/babel-plugin-transform-named-imports#2]
For large codebases, this plugin ends up being a little slow since it might re-resolve a popular file many times. It might make sense to set up some sort of cache that can be shared between instances of the loader.

A possible implementation idea:

cache key = directory context + required path
cache value = resolved path

So for the file `/Users/Someone/code/project/src/blah/blah/blah/index.js` containing:

```js
import { Foo } from '../../index.js';
```

The cache entry would look like:

```
'/Users/Someone/code/project/src/blah/blah/blah:../../index.js': '/Users/Someone/code/project/src/blah/index.js'
```

(the colon seems to invalid in most file systems, so a good candidate for a delimiter)

Then all siblings to `/Users/Someone/code/project/src/blah/blah/blah/index.js` could make use of the cache. With some finessing, it might be possible for the cache to be usable by children in other directory contexts...

**Comment by Photonios** [comment]
Fixed and released in 1.0.2-beta:

https://github.com/SectorLabs/babel-plugin-transform-named-imports/releases/tag/v1.0.2-beta
