### ISSUE TITLE
Handle renaming of imports

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [SectorLabs/babel-plugin-transform-named-imports#3]
With a file chain like:

```js
// index.js
import { PlansView } from './Items';

// Items/index.js
import { PlansConnector as PlansView } from './PlansConnector';

export { PlansView };

// PlansConnector/index.js
export const PlansConnector = connect(
    mapStateToProps,
    mapDispatchToProps
)(ItemsView);
```

The plugin is still looking for `"PlansView"` when it gets to `PlansConnector/index.js`, which won't exist since the import was renamed.

I imagine renaming `default` probably wouldn't work either under the current implementation.

**Comment by Photonios** [comment]
Fixed and released in 1.0.2-beta:

https://github.com/SectorLabs/babel-plugin-transform-named-imports/releases/tag/v1.0.2-beta
