### ISSUE TITLE
incorrect handling of namespace renamed export

### ISSUE THREAD

**Issue by hansololai** [SectorLabs/babel-plugin-transform-named-imports#6]
The program searches for import with the candidate name first, then if not found, it will look for re-export. 

This logic has a problem:  for example, 
testmodule/index.js
`import myFunc from './myFunc';`
`import { myOtherOtherFunc } from './reexport';`
`import * as things from './constants';`

`export {`
`  myFunc,`
`  myOtherOtherFunc as myOtherFunc,`
`  things as thangs,`
`  myFunc as things,`
`};`

When the program searches for import of things, it will convert a import string

>  `import { things } from 'testmodule'`,

into

>  `import * as  things  from './tests/testmodule/constants'`,

while infact, it should be 

> `import  things from './tests/testmodule/myFunc'`

Another problem of this logic is:
It does not handle export from syntax

If testmodule/index.js contains

export {Foo2} from '/Foo.js';

The program could not find it because the re-export it handles must be separate import and export. 

PR #7

**Comment by Photonios** [comment]
This does not indicate breakage. The import gets transformed to that because you're exporting two things with the same name. It exports `myFunc` twice.
